name: build-action

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup Checkout autoproj CI
        uses: actions/checkout@v2
        with:
          repository: Brazilian-Institute-of-Robotics/bir-autoproj-action
          ssh-key: ${{ secrets.AUTOPROJ_ACTION_TOKEN }}
      - uses: ./
        with:
          distro: bionic
          buildconf-url: git@github.com:romulogcerqueira/sonar_simulation.git
          packages: '${{ github.event.repository.name }}'
          seed-config: |
            ---
            apt_dpkg_update: 'true'
            osdeps_mode: all
            GITORIOUS: ssh
            GITHUB: ssh
            ROCK_SELECTED_FLAVOR: master
            ROCK_FLAVOR: master
            ROCK_BRANCH: master
            USE_OCL: false
            rtt_corba_implementation: omniorb
            rtt_target: gnulinux
            cxx11: false
